language: node_js
node_js: '8'
before_script: npm install -g wspackager
script: wspackager
branches:
  only: master
git:
  depth: 5
env:
  global:
  - IDENTIFIER=com.clanunknownsoldiers.plugin.pages.tar
  - FTP_HOST=ftp://thunderstorm.unkso.com
  - secure: MoiBIsffH/QrH4YlSnghfcK0MPv5JAcl8RJ41P0gXYB/yYpc66MBrp4NF8KiRt41Kq3pl7xEqh5vT3/55eKj4J2qJ92eVHm4UDorCSbt6P66vuqQTmQzitnp3Z2bkYyzUSAGKYkDnFaUx47CKFNCbiX1++jUAfG5b38BMHE90TQx2ye2w/RrReaklREZJuZLQhucgTslNfAH67180cVy3MW/kAEt4Pkqd4TZn10e59PCZXxRZF9hbwNW/7yEpI7Z52RQg+Bn1ECq1XyR9Qs9WDu5pAN6mq+FqPcsySuj3oMBmHRm+mPE8Zuy98JyPa4kcpM1NyI5f4+KBVyvK+GSqR0S9OkttxEZNWfN5k6/syflpSbo5FHu3E5w3KmZuo5OrFER62SAX6uZpIkWtXa6LqE/t1SbN0HHklFQZ/syGn50B22tLN5EL22LUR2lFITDpckH+rnnqxXMoQ4MGznj5IyLWZxJFCkg5bbLSvZsnUP0ozifS+JjSlEHB5RZ0GaEeqeMoYhnIicY2ViZNQUcy+aVva9W5pZKeSgyv2+y6RHmmJshJwuQViFiy6nc/LcV4gD6qG9WAEueg43L6JGvvrMYuP6sN5rDoJ3e/TL+RQaaIAbpd+7POp76maMWyOrUq3fJT/LVIFTo3VXY7Ex3jmu/GuDIXX+zrjuX+2IrS9A=
  - secure: DyiN4gbcwlvWiZGIfx9QXoFjhEwYmp3i8kaVW+nHy9yZvUhBakFhCzq7sxZY1aZJXU5V3ruKdOO7eMuDcc7ZN8kbPh2wzy3/YEKRfyJBuVEQOolvTACTxceGObU5p90ZmOSQRNURHPVUlJ61vShM6rXi0PbLDsswdrY+js0wiwRfVNnZTu9b4bx7HeF7EceYwPkbDwD4ApdUjazCHtLBRK6UEITvrwdaK/6eETcLfJlkqYrn9lXUTa893G8WUI76WO5m3U8qsHvPb1N0ZKcw9zaEi7z+9x7cCBw7K2tFhuc1Uziu0QBPrlsq/3SL1EjCXAAMovh9c7ptyn0oOAQktJ5BGEERkfVYis0mO5VRyQ/kwlBOCF53cupuMytZsMnnKOuRMcS0UZ++zDJMnldzOGJwqf0QYyYHXVRveGWhpXfkTKmL2tfZQ/+j1NxBb5maqORLyb9oBxKhNimesT1/266ub1M6ekNv1jKijY86X/3IWSEvefty/jaCUnuqdBIGsb2MhxqLstzmjSydwa/oPo9lskVKIWmIPWoSGtxUMwM9VCKbuZcCzZxrT2j52nx5ThbQ2VOiRVAQTxaVEodbhUnp190yn63p91t3yBIVYhMh9WLzr4mhcnjZRYL4K3pFcAi35UKljOZoml8C4NU+Wx8ZEUknwX2E3zMnXiOMNec=
notifications:
  email: false
after_success: curl --ftp-create-dirs -T $IDENTIFIER -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
